<?php
/* @var $block \FourTell\Recommend\Block\Html\Loader */

if ($block->isConfigEnable()):
    $jsCode = $block->getJsLoader();
    $jsCode = str_replace("MODE", $block->getConfigMode(), $jsCode);
    $jsCode = str_replace("CLIENT_ALIAS", $block->getConfigAlias(), $jsCode);
    $extraData = $block->getExtraData();
    $jsCode = str_replace("//4-TELL_EXTRA_CODE", $extraData, $jsCode);
    echo $jsCode;
endif;